### ISSUE TITLE
Downloading the DFDC and DFDC Preview datasets

### ISSUE THREAD

**Issue by bysen32** [QingyuLiu/Exposing-the-Deception#3]
Hello, sorry to bother you. Could you please provide the download links for the DFDC and DFDC Preview test datasets on a file-sharing platform?
I have been trying for a long time but have been unable to successfully register on the official website(https://dfdc.ai/sign-up). I would greatly appreciate your help.

**Comment by QingyuLiu** [comment]
I'm sorry that the file may not be uploaded to Baidu Cloud quickly because it is too large. If you also use the WeChat app, you can add me on WeChat and I will share the official website account with you and download it. My WeChat ID is `Liu_C_Xu` (please note the purpose).
