### ISSUE TITLE
Questions about test sets. 

### ISSUE THREAD

**Issue by thatc** [QingyuLiu/Exposing-the-Deception#5]
Is the DFDC-P dataset using the entire dataset of 1131 real videos and 4119 faked videos in the model testing phase?
Thanks for your work, it helps me a lot!

**Comment by QingyuLiu** [comment]
Yes, in the cross-dataset setting, we use all videos of the unknown dataset, note that we randomly select 30 frames for each video. Anyway, I'm really glad our research helped you.
